import type { NursingSpecialty, State } from 'src/types/nurse';
import type { NurseData } from 'src/types/types';

export const nurseData: NurseData[] = [
  {
    id: '1',
    user: 'dan***',
    specialty: 'PICU',
    location: 'Brooklyn, NY',
    experience: '2 - 3 years',
    shiftType: 'Night',
    basePay: 58.5,
    differentials: 4.5,
    totalPay: 63,
  },
  {
    id: '2',
    user: 'su8***',
    specialty: 'Pediatrics',
    location: 'Manhattan, NY',
    experience: '5 - 10 years',
    shiftType: 'Day',
    basePay: 75,
    differentials: 5,
    totalPay: 80,
  },
  {
    id: '3',
    user: 'rn2***',
    specialty: 'ER',
    location: 'Queens, NY',
    experience: '10+ years',
    shiftType: 'Night',
    basePay: 85,
    differentials: 7.5,
    totalPay: 92.5,
  },
  {
    id: '4',
    user: 'med***',
    specialty: 'Med-Surg',
    location: 'Bronx, NY',
    experience: '0 - 2 years',
    shiftType: 'Day',
    basePay: 45,
    differentials: 3,
    totalPay: 48,
  },
  {
    id: '5',
    user: 'icu***',
    specialty: 'ICU',
    location: 'Staten Island, NY',
    experience: '3 - 5 years',
    shiftType: 'Night',
    basePay: 65,
    differentials: 6,
    totalPay: 71,
  },
  {
    id: '6',
    user: 'ld1***',
    specialty: 'L&D',
    location: 'Brooklyn, NY',
    experience: '5 - 10 years',
    shiftType: 'Night',
    basePay: 78,
    differentials: 6.5,
    totalPay: 84.5,
  },
  {
    id: '7',
    user: 'or2***',
    specialty: 'OR',
    location: 'Manhattan, NY',
    experience: '3 - 5 years',
    shiftType: 'Day',
    basePay: 70,
    differentials: 4,
    totalPay: 74,
  },
  {
    id: '8',
    user: 'nicu***',
    specialty: 'NICU',
    location: 'Queens, NY',
    experience: '2 - 3 years',
    shiftType: 'Night',
    basePay: 62,
    differentials: 5.5,
    totalPay: 67.5,
  },
  {
    id: '9',
    user: 'ped2***',
    specialty: 'Pediatrics',
    location: 'Bronx, NY',
    experience: '10+ years',
    shiftType: 'Day',
    basePay: 82,
    differentials: 5,
    totalPay: 87,
  },
  {
    id: '10',
    user: 'er5***',
    specialty: 'ER',
    location: 'Staten Island, NY',
    experience: '5 - 10 years',
    shiftType: 'Night',
    basePay: 76,
    differentials: 7,
    totalPay: 83,
  },
  {
    id: '11',
    user: 'picu2***',
    specialty: 'PICU',
    location: 'Brooklyn, NY',
    experience: '0 - 2 years',
    shiftType: 'Day',
    basePay: 48,
    differentials: 3,
    totalPay: 51,
  },
  {
    id: '12',
    user: 'icu7***',
    specialty: 'ICU',
    location: 'Manhattan, NY',
    experience: '3 - 5 years',
    shiftType: 'Night',
    basePay: 68,
    differentials: 6,
    totalPay: 74,
  },
  {
    id: '13',
    user: 'or9***',
    specialty: 'OR',
    location: 'Queens, NY',
    experience: '5 - 10 years',
    shiftType: 'Day',
    basePay: 72,
    differentials: 4.5,
    totalPay: 76.5,
  },
  {
    id: '14',
    user: 'ld4***',
    specialty: 'L&D',
    location: 'Bronx, NY',
    experience: '10+ years',
    shiftType: 'Night',
    basePay: 88,
    differentials: 7.5,
    totalPay: 95.5,
  },
  {
    id: '15',
    user: 'nicu5***',
    specialty: 'NICU',
    location: 'Staten Island, NY',
    experience: '2 - 3 years',
    shiftType: 'Day',
    basePay: 60,
    differentials: 4,
    totalPay: 64,
  },
];

export const statesData = [
  { value: 'AL', label: 'Alabama', region: 'South', avgSalary: 440000 },
  { value: 'AK', label: 'Alaska', region: 'West', avgSalary: 495000 },
  { value: 'AZ', label: 'Arizona', region: 'West', avgSalary: 455000 },
  { value: 'AR', label: 'Arkansas', region: 'South', avgSalary: 435000 },
  { value: 'CA', label: 'California', region: 'West', avgSalary: 490000 },
  { value: 'CO', label: 'Colorado', region: 'West', avgSalary: 460000 },
  { value: 'CT', label: 'Connecticut', region: 'Northeast', avgSalary: 475000 },
  { value: 'DE', label: 'Delaware', region: 'South', avgSalary: 455000 },
  { value: 'FL', label: 'Florida', region: 'South', avgSalary: 455000 },
  { value: 'GA', label: 'Georgia', region: 'South', avgSalary: 450000 },
  { value: 'HI', label: 'Hawaii', region: 'West', avgSalary: 485000 },
  { value: 'ID', label: 'Idaho', region: 'West', avgSalary: 445000 },
  { value: 'IL', label: 'Illinois', region: 'Midwest', avgSalary: 450000 },
  { value: 'IN', label: 'Indiana', region: 'Midwest', avgSalary: 440000 },
  { value: 'IA', label: 'Iowa', region: 'Midwest', avgSalary: 435000 },
  { value: 'KS', label: 'Kansas', region: 'Midwest', avgSalary: 440000 },
  { value: 'KY', label: 'Kentucky', region: 'South', avgSalary: 435000 },
  { value: 'LA', label: 'Louisiana', region: 'South', avgSalary: 440000 },
  { value: 'ME', label: 'Maine', region: 'Northeast', avgSalary: 445000 },
  { value: 'MD', label: 'Maryland', region: 'South', avgSalary: 465000 },
  {
    value: 'MA',
    label: 'Massachusetts',
    region: 'Northeast',
    avgSalary: 470000,
  },
  { value: 'MI', label: 'Michigan', region: 'Midwest', avgSalary: 445000 },
  { value: 'MN', label: 'Minnesota', region: 'Midwest', avgSalary: 455000 },
  { value: 'MS', label: 'Mississippi', region: 'South', avgSalary: 435000 },
  { value: 'MO', label: 'Missouri', region: 'Midwest', avgSalary: 440000 },
  { value: 'MT', label: 'Montana', region: 'West', avgSalary: 445000 },
  { value: 'NE', label: 'Nebraska', region: 'Midwest', avgSalary: 440000 },
  { value: 'NV', label: 'Nevada', region: 'West', avgSalary: 460000 },
  {
    value: 'NH',
    label: 'New Hampshire',
    region: 'Northeast',
    avgSalary: 455000,
  },
  { value: 'NJ', label: 'New Jersey', region: 'Northeast', avgSalary: 475000 },
  { value: 'NM', label: 'New Mexico', region: 'West', avgSalary: 445000 },
  { value: 'NY', label: 'New York', region: 'Northeast', avgSalary: 485000 },
  { value: 'NC', label: 'North Carolina', region: 'South', avgSalary: 445000 },
  { value: 'ND', label: 'North Dakota', region: 'Midwest', avgSalary: 440000 },
  { value: 'OH', label: 'Ohio', region: 'Midwest', avgSalary: 445000 },
  { value: 'OK', label: 'Oklahoma', region: 'South', avgSalary: 440000 },
  { value: 'OR', label: 'Oregon', region: 'West', avgSalary: 465000 },
  {
    value: 'PA',
    label: 'Pennsylvania',
    region: 'Northeast',
    avgSalary: 460000,
  },
  {
    value: 'RI',
    label: 'Rhode Island',
    region: 'Northeast',
    avgSalary: 465000,
  },
  { value: 'SC', label: 'South Carolina', region: 'South', avgSalary: 440000 },
  { value: 'SD', label: 'South Dakota', region: 'Midwest', avgSalary: 435000 },
  { value: 'TN', label: 'Tennessee', region: 'South', avgSalary: 440000 },
  { value: 'TX', label: 'Texas', region: 'South', avgSalary: 460000 },
  { value: 'UT', label: 'Utah', region: 'West', avgSalary: 450000 },
  { value: 'VT', label: 'Vermont', region: 'Northeast', avgSalary: 450000 },
  { value: 'VA', label: 'Virginia', region: 'South', avgSalary: 455000 },
  { value: 'WA', label: 'Washington', region: 'West', avgSalary: 475000 },
  { value: 'WV', label: 'West Virginia', region: 'South', avgSalary: 435000 },
  { value: 'WI', label: 'Wisconsin', region: 'Midwest', avgSalary: 445000 },
  { value: 'WY', label: 'Wyoming', region: 'West', avgSalary: 445000 },
].sort((a, b) => a.label.localeCompare(b.label)) as Array<State>;

export const nursingSpecialtyData: NursingSpecialty[] = [
  {
    specialty: 'Travel Nursing',
    'Base Pay': 450000,
    'Differential Pay': 90000,
    total: 540000,
    state: 'CA',
  },
  {
    specialty: 'Labor & Delivery',
    'Base Pay': 440000,
    'Differential Pay': 85000,
    total: 525000,
    state: 'NY',
  },
  {
    specialty: 'Intensive Care Unit (ICU)',
    'Base Pay': 435000,
    'Differential Pay': 85000,
    total: 520000,
    state: 'CA',
  },
  {
    specialty: 'Psychiatric',
    'Base Pay': 420000,
    'Differential Pay': 80000,
    total: 500000,
    state: 'WA',
  },
  {
    specialty: 'Cardiology',
    'Base Pay': 425000,
    'Differential Pay': 75000,
    total: 500000,
    state: 'MA',
  },
  {
    specialty: 'Telemetry',
    'Base Pay': 410000,
    'Differential Pay': 80000,
    total: 490000,
    state: 'TX',
  },
  {
    specialty: 'Orthopedics',
    'Base Pay': 405000,
    'Differential Pay': 80000,
    total: 485000,
    state: 'FL',
  },
  {
    specialty: 'Oncology',
    'Base Pay': 405000,
    'Differential Pay': 80000,
    total: 485000,
    state: 'IL',
  },
  {
    specialty: 'Emergency Room (ER)',
    'Base Pay': 405000,
    'Differential Pay': 80000,
    total: 485000,
    state: 'NY',
  },
  {
    specialty: 'Dialysis',
    'Base Pay': 390000,
    'Differential Pay': 80000,
    total: 470000,
    state: 'CA',
  },
  {
    specialty: 'Surgery',
    'Base Pay': 380000,
    'Differential Pay': 80000,
    total: 460000,
    state: 'TX',
  },
  {
    specialty: 'Operating Room (OR)',
    'Base Pay': 370000,
    'Differential Pay': 80000,
    total: 450000,
    state: 'FL',
  },
  {
    specialty: 'Critical Care',
    'Base Pay': 370000,
    'Differential Pay': 80000,
    total: 450000,
    state: 'CA',
  },
  {
    specialty: 'Neonatal',
    'Base Pay': 355000,
    'Differential Pay': 80000,
    total: 435000,
    state: 'NY',
  },
  {
    specialty: 'Rehabilitation',
    'Base Pay': 340000,
    'Differential Pay': 80000,
    total: 420000,
    state: 'IL',
  },
  {
    specialty: 'Pediatrics',
    'Base Pay': 340000,
    'Differential Pay': 80000,
    total: 420000,
    state: 'CA',
  },
  {
    specialty: 'Home Health',
    'Base Pay': 335000,
    'Differential Pay': 70000,
    total: 405000,
    state: 'TX',
  },
  {
    specialty: 'Geriatrics',
    'Base Pay': 320000,
    'Differential Pay': 70000,
    total: 390000,
    state: 'FL',
  },
  {
    specialty: 'School Nurse',
    'Base Pay': 310000,
    'Differential Pay': 70000,
    total: 380000,
    state: 'NY',
  },
  {
    specialty: 'Nurse Educator',
    'Base Pay': 300000,
    'Differential Pay': 65000,
    total: 365000,
    state: 'CA',
  },
].sort((a, b) => b.total - a.total);

export const regionGroupsData = {
  Northeast: statesData.filter((state) => state.region === 'Northeast'),
  South: statesData.filter((state) => state.region === 'South'),
  Midwest: statesData.filter((state) => state.region === 'Midwest'),
  West: statesData.filter((state) => state.region === 'West'),
};
