import type { NurseData } from 'src/types/types';

const nurseData: NurseData[] = [
  {
    id: '1',
    user: 'dan***',
    specialty: 'PICU',
    location: 'Brooklyn, NY',
    experience: '2 - 3 years',
    shiftType: 'Night',
    basePay: 58.5,
    differentials: 4.5,
    totalPay: 63,
  },
  {
    id: '2',
    user: 'su8***',
    specialty: 'Pediatrics',
    location: 'Manhattan, NY',
    experience: '5 - 10 years',
    shiftType: 'Day',
    basePay: 75,
    differentials: 5,
    totalPay: 80,
  },
  {
    id: '3',
    user: 'rn2***',
    specialty: 'ER',
    location: 'Queens, NY',
    experience: '10+ years',
    shiftType: 'Night',
    basePay: 85,
    differentials: 7.5,
    totalPay: 92.5,
  },
  {
    id: '4',
    user: 'med***',
    specialty: 'Med-Surg',
    location: 'Bronx, NY',
    experience: '0 - 2 years',
    shiftType: 'Day',
    basePay: 45,
    differentials: 3,
    totalPay: 48,
  },
  {
    id: '5',
    user: 'icu***',
    specialty: 'ICU',
    location: 'Staten Island, NY',
    experience: '3 - 5 years',
    shiftType: 'Night',
    basePay: 65,
    differentials: 6,
    totalPay: 71,
  },
  {
    id: '6',
    user: 'ld1***',
    specialty: 'L&D',
    location: 'Brooklyn, NY',
    experience: '5 - 10 years',
    shiftType: 'Night',
    basePay: 78,
    differentials: 6.5,
    totalPay: 84.5,
  },
  {
    id: '7',
    user: 'or2***',
    specialty: 'OR',
    location: 'Manhattan, NY',
    experience: '3 - 5 years',
    shiftType: 'Day',
    basePay: 70,
    differentials: 4,
    totalPay: 74,
  },
  {
    id: '8',
    user: 'nicu***',
    specialty: 'NICU',
    location: 'Queens, NY',
    experience: '2 - 3 years',
    shiftType: 'Night',
    basePay: 62,
    differentials: 5.5,
    totalPay: 67.5,
  },
  {
    id: '9',
    user: 'ped2***',
    specialty: 'Pediatrics',
    location: 'Bronx, NY',
    experience: '10+ years',
    shiftType: 'Day',
    basePay: 82,
    differentials: 5,
    totalPay: 87,
  },
  {
    id: '10',
    user: 'er5***',
    specialty: 'ER',
    location: 'Staten Island, NY',
    experience: '5 - 10 years',
    shiftType: 'Night',
    basePay: 76,
    differentials: 7,
    totalPay: 83,
  },
  {
    id: '11',
    user: 'picu2***',
    specialty: 'PICU',
    location: 'Brooklyn, NY',
    experience: '0 - 2 years',
    shiftType: 'Day',
    basePay: 48,
    differentials: 3,
    totalPay: 51,
  },
  {
    id: '12',
    user: 'icu7***',
    specialty: 'ICU',
    location: 'Manhattan, NY',
    experience: '3 - 5 years',
    shiftType: 'Night',
    basePay: 68,
    differentials: 6,
    totalPay: 74,
  },
  {
    id: '13',
    user: 'or9***',
    specialty: 'OR',
    location: 'Queens, NY',
    experience: '5 - 10 years',
    shiftType: 'Day',
    basePay: 72,
    differentials: 4.5,
    totalPay: 76.5,
  },
  {
    id: '14',
    user: 'ld4***',
    specialty: 'L&D',
    location: 'Bronx, NY',
    experience: '10+ years',
    shiftType: 'Night',
    basePay: 88,
    differentials: 7.5,
    totalPay: 95.5,
  },
  {
    id: '15',
    user: 'nicu5***',
    specialty: 'NICU',
    location: 'Staten Island, NY',
    experience: '2 - 3 years',
    shiftType: 'Day',
    basePay: 60,
    differentials: 4,
    totalPay: 64,
  },
];

export default nurseData;
